version: 1
disable_existing_loggers: True
formatters:
  standard:
    style: "{"
    format: "{asctime} [{levelname}] {filename}:{lineno} {threadName} - {message}"
handlers:
  default:
    # level: INFO
    formatter: standard
    class: logging.StreamHandler
loggers:
  '':
    handlers: ['default']
    level: INFO
    propagate: false