name: Build and test
on: 
  - workflow_dispatch
  - pull_request

jobs:
  build-and-test-python:
    strategy:
      matrix:
        project:
          - api
          - cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install UV
        id: install-uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build
        id: build
        working-directory: ${{ matrix.project }}
        run: uv sync && uv build
      