on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: |
          commit_log=$(mktemp)
          update_level=$(mktemp)
          git log --quiet HEAD^..HEAD > $commit_log
          update_level=$(grep -q '[major]' $commit_log && echo 'major' || \
            grep -q '[minor]' $commit_log && echo 'minor' || \
            grep -q '[patch]' $commit_log && echo 'patch' || \
            echo "none" > $update_level)

          echo "Update level is $(cat $update_level)"