name: Release - Create

on:
  workflow_dispatch:

jobs:
  release-create:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create a release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Configure github actions name and email
        id: configre-gha-name-email
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install uv
        id: install-uv
        shell: bash
        run: make install-uv

      - uses: actions/setup-node@v6
        with:
          node-version: 23

      - name: Version Bump (to stable)
        id: bump-version
        working-directory: api
        if: false
        run: |
          update_log=$(mktemp)

          uv version --bump stable | tee $update_log
          echo "new-version=$(uv version --short)" >> $GITHUB_OUTPUT
          echo "update-message=$(tail -n1 $update_log)" >> $GITHUB_OUTPUT
          
      - name: Build dist package
        if: false
        run: make clean all

      - name: Create release commit
        id: release-commit
        if: false
        run: |
          if ! git diff-files --quiet; then
            echo "version-bumped=true" >> $GITHUB_OUTPUT
            
            # Push release commit
            git add -A .
            git commit -am "Version bump ${{ steps.bump-version.outputs.update-message }}"
            git push
          else
            echo "version-bumped=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to PyPi
        id: publsh-to-pypi
        # if: ${{ steps.release-commit.outputs.version-bumped == 'true' }}
        working-directory: api
        run: uv publish

      - name: Create GitHub release
        id: publish-to-github
        # if: ${{ steps.release-commit.outputs.version-bumped == 'true' }}
        run: |
          # Get new version
          new_version=$(uv --project api version --short)

          gh release create "$new_version" --generate-notes
          gh release upload "$new_version" api/dist/*

          # Update latest tag
          git tag --force latest
          git push --force --tags