name: _ TEST WORKFLOW

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push the version bump back to the repo
    steps:
      - name: Bump version
        run: gh --help